libecs-cpp: nlohmann::detail::parser< BasicJsonType, InputAdapterType > Class Template Reference
nlohmann::detail::parser< BasicJsonType, InputAdapterType > Class Template Reference
syntax analysis
#include <json.hpp>
Public Member Functions
parser (InputAdapterType &&adapter, const parser_callback_t< BasicJsonType > cb=nullptr, const bool allow_exceptions_=true, const bool skip_comments=false)
a parser reading from an input adapter
void parse (const bool strict, BasicJsonType &result)
public parser interface
bool accept (const bool strict=true)
public accept interface
template<typename SAX >
bool sax_parse (SAX *sax, const bool strict=true)
Private Types
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using number_float_t = typename BasicJsonType::number_float_t
using string_t = typename BasicJsonType::string_t
using lexer_t = lexer< BasicJsonType, InputAdapterType >
using token_type = typename lexer_t::token_type
Private Member Functions
template<typename SAX >
bool sax_parse_internal (SAX *sax)
token_type get_token ()
get next token from lexer
std::string exception_message (const token_type expected, const std::string &context)
Private Attributes
const parser_callback_t< BasicJsonType > callback = nullptr
callback function
token_type last_token = token_type::uninitialized
the type of the last read token
lexer_t m_lexer
the lexer
const bool allow_exceptions = true
whether to throw exceptions in case of errors
Detailed Description
template<typename BasicJsonType, typename InputAdapterType>
class nlohmann::detail::parser< BasicJsonType, InputAdapterType >
syntax analysis
This class implements a recursive descent parser.
Definition at line 10759 of file json.hpp.
Member Typedef Documentation
lexer_t
template<typename BasicJsonType , typename InputAdapterType > using nlohmann::detail::parser< BasicJsonType, InputAdapterType >::lexer_t = lexer<BasicJsonType, InputAdapterType> private
Definition at line 10765 of file json.hpp.
number_float_t
template<typename BasicJsonType , typename InputAdapterType > using nlohmann::detail::parser< BasicJsonType, InputAdapterType >::number_float_t = typename BasicJsonType::number_float_t private
Definition at line 10763 of file json.hpp.
number_integer_t
template<typename BasicJsonType , typename InputAdapterType > using nlohmann::detail::parser< BasicJsonType, InputAdapterType >::number_integer_t = typename BasicJsonType::number_integer_t private
Definition at line 10761 of file json.hpp.
number_unsigned_t
template<typename BasicJsonType , typename InputAdapterType > using nlohmann::detail::parser< BasicJsonType, InputAdapterType >::number_unsigned_t = typename BasicJsonType::number_unsigned_t private
Definition at line 10762 of file json.hpp.
string_t
template<typename BasicJsonType , typename InputAdapterType > using nlohmann::detail::parser< BasicJsonType, InputAdapterType >::string_t = typename BasicJsonType::string_t private
Definition at line 10764 of file json.hpp.
token_type
template<typename BasicJsonType , typename InputAdapterType > using nlohmann::detail::parser< BasicJsonType, InputAdapterType >::token_type = typename lexer_t::token_type private
Definition at line 10766 of file json.hpp.
Constructor & Destructor Documentation
parser()
template<typename BasicJsonType , typename InputAdapterType > nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parser (InputAdapterType && adapter, const parser_callback_t< BasicJsonType > cb = nullptr, const bool allow_exceptions_ = true, const bool skip_comments = false) inline explicit
a parser reading from an input adapter
Definition at line 10770 of file json.hpp.
        : callback(cb)
        , m_lexer(std::move(adapter), skip_comments)
        , allow_exceptions(allow_exceptions_)
    {
        // read first token
        get_token();
    }
References nlohmann::detail::parser< BasicJsonType, InputAdapterType >::get_token().
Member Function Documentation
accept()
template<typename BasicJsonType , typename InputAdapterType > bool nlohmann::detail::parser< BasicJsonType, InputAdapterType >::accept (const bool strict = true) inline
public accept interface
Parameters
[in] strict whether to expect the last token to be EOF
Returns
whether the input is a proper JSON text
Definition at line 10852 of file json.hpp.
    {
        json_sax_acceptor<BasicJsonType> sax_acceptor;
        return sax_parse(&sax_acceptor, strict);
    }
References nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse(), and nlohmann::detail::strict.
exception_message()
template<typename BasicJsonType , typename InputAdapterType > std::string nlohmann::detail::parser< BasicJsonType, InputAdapterType >::exception_message (const token_type expected, const std::string & context) inline private
Definition at line 11165 of file json.hpp.
    {
        std::string error_msg = "syntax error ";
        if (!context.empty())
        {
            error_msg += "while parsing " + context + " ";
        }
        error_msg += "- ";
        if (last_token == token_type::parse_error)
        {
            error_msg += std::string(m_lexer.get_error_message()) + "; last read: '" +
                         m_lexer.get_token_string() + "'";
        }
        else
        {
            error_msg += "unexpected " + std::string(lexer_t::token_type_name(last_token));
        }
        if (expected != token_type::uninitialized)
        {
            error_msg += "; expected " + std::string(lexer_t::token_type_name(expected));
        }
        return error_msg;
    }
References nlohmann::detail::lexer< BasicJsonType, InputAdapterType >::get_error_message(), nlohmann::detail::lexer< BasicJsonType, InputAdapterType >::get_token_string(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::last_token, nlohmann::detail::parser< BasicJsonType, InputAdapterType >::m_lexer, and nlohmann::detail::lexer_base< BasicJsonType >::token_type_name().
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse(), and nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal().
get_token()
template<typename BasicJsonType , typename InputAdapterType > token_type nlohmann::detail::parser< BasicJsonType, InputAdapterType >::get_token () inline private
get next token from lexer
Definition at line 11160 of file json.hpp.
    {
        return last_token = m_lexer.scan();
    }
References nlohmann::detail::parser< BasicJsonType, InputAdapterType >::last_token, nlohmann::detail::parser< BasicJsonType, InputAdapterType >::m_lexer, and nlohmann::detail::lexer< BasicJsonType, InputAdapterType >::scan().
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parser(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse(), and nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal().
parse()
template<typename BasicJsonType , typename InputAdapterType > void nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse (const bool strict, BasicJsonType & result) inline
public parser interface
Parameters
[in] strict whether to expect the last token to be EOF
[in,out] result parsed JSON value
Exceptions
parse_error.101 in case of an unexpected token
parse_error.102 if to_unicode fails or surrogate error
parse_error.103 if to_unicode fails
Definition at line 10792 of file json.hpp.
    {
        if (callback)
        {
            json_sax_dom_callback_parser<BasicJsonType> sdp(result, callback, allow_exceptions);
            sax_parse_internal(&sdp);
            // in strict mode, input must be completely read
            if (strict && (get_token() != token_type::end_of_input))
            {
                sdp.parse_error(m_lexer.get_position(),
                                m_lexer.get_token_string(),
                                parse_error::create(101, m_lexer.get_position(),
                                                    exception_message(token_type::end_of_input, "value"), BasicJsonType()));
            }
            // in case of an error, return discarded value
            if (sdp.is_errored())
            {
                result = value_t::discarded;
                return;
            }
            // set top-level value to null if it was discarded by the callback
            // function
            if (result.is_discarded())
            {
                result = nullptr;
            }
        }
        else
        {
            json_sax_dom_parser<BasicJsonType> sdp(result, allow_exceptions);
            sax_parse_internal(&sdp);
            // in strict mode, input must be completely read
            if (strict && (get_token() != token_type::end_of_input))
            {
                sdp.parse_error(m_lexer.get_position(),
                                m_lexer.get_token_string(),
                                parse_error::create(101, m_lexer.get_position(), exception_message(token_type::end_of_input, "value"), BasicJsonType()));
            }
            // in case of an error, return discarded value
            if (sdp.is_errored())
            {
                result = value_t::discarded;
                return;
            }
        }
        result.assert_invariant();
    }
References nlohmann::detail::parser< BasicJsonType, InputAdapterType >::allow_exceptions, nlohmann::detail::parser< BasicJsonType, InputAdapterType >::callback, nlohmann::detail::parse_error::create(), nlohmann::detail::discarded, nlohmann::detail::parser< BasicJsonType, InputAdapterType >::exception_message(), nlohmann::detail::lexer< BasicJsonType, InputAdapterType >::get_position(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::get_token(), nlohmann::detail::lexer< BasicJsonType, InputAdapterType >::get_token_string(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::is_errored(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::is_errored(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::m_lexer, nlohmann::detail::json_sax_dom_parser< BasicJsonType >::parse_error(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::parse_error(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal(), and nlohmann::detail::strict.
sax_parse()
template<typename BasicJsonType , typename InputAdapterType > template<typename SAX > bool nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse (SAX * sax, const bool strict = true) inline
Definition at line 10860 of file json.hpp.
    {
        (void)detail::is_sax_static_asserts<SAX, BasicJsonType> {};
        const bool result = sax_parse_internal(sax);
        // strict mode: next byte must be EOF
        if (result && strict && (get_token() != token_type::end_of_input))
        {
            return sax->parse_error(m_lexer.get_position(),
                                    m_lexer.get_token_string(),
                                    parse_error::create(101, m_lexer.get_position(), exception_message(token_type::end_of_input, "value"), BasicJsonType()));
        }
        return result;
    }
References nlohmann::detail::parse_error::create(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::exception_message(), nlohmann::detail::lexer< BasicJsonType, InputAdapterType >::get_position(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::get_token(), nlohmann::detail::lexer< BasicJsonType, InputAdapterType >::get_token_string(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::m_lexer, nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal(), and nlohmann::detail::strict.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::accept().
sax_parse_internal()
template<typename BasicJsonType , typename InputAdapterType > template<typename SAX > bool nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal (SAX * sax) inline private
Definition at line 10879 of file json.hpp.
    {
        // stack to remember the hierarchy of structured values we are parsing
        // true = array; false = object
        std::vector<bool> states;
        // value to avoid a goto (see comment where set to true)
        bool skip_to_state_evaluation = false;
        while (true)
        {
            if (!skip_to_state_evaluation)
            {
                // invariant: get_token() was called before each iteration
                switch (last_token)
                {
                    case token_type::begin_object:
                    {
                        if (JSON_HEDLEY_UNLIKELY(!sax->start_object(static_cast<std::size_t>(-1))))
{
                            return false;
                        }
                        // closing } -> we are done
                        if (get_token() == token_type::end_object)
{
                            if (JSON_HEDLEY_UNLIKELY(!sax->end_object()))
{
                                return false;
                            }
                            break;
                        }
                        // parse key
                        if (JSON_HEDLEY_UNLIKELY(last_token != token_type::value_string))
{
                            return sax->parse_error(m_lexer.get_position(),
                                                    m_lexer.get_token_string(),
                                                    parse_error::create(101, m_lexer.get_position(), exception_message(token_type::value_string, "object key"), BasicJsonType()));
                        }
                        if (JSON_HEDLEY_UNLIKELY(!sax->key(m_lexer.get_string())))
{
                            return false;
                        }
                        // parse separator (:)
                        if (JSON_HEDLEY_UNLIKELY(get_token() != token_type::name_separator))
{
                            return sax->parse_error(m_lexer.get_position(),
                                                    m_lexer.get_token_string(),
                                                    parse_error::create(101, m_lexer.get_position(), exception_message(token_type::name_separator, "object separator"), BasicJsonType()));
                        }
                        // remember we are now inside an object
                        states.push_back(false);
                        // parse values
                        get_token();
                        continue;
                    }
                    case token_type::begin_array:
                    {
                        if (JSON_HEDLEY_UNLIKELY(!sax->start_array(static_cast<std::size_t>(-1))))
{
                            return false;
                        }
                        // closing ] -> we are done
                        if (get_token() == token_type::end_array)
{
                            if (JSON_HEDLEY_UNLIKELY(!sax->end_array()))
{
                                return false;
                            }
                            break;
                        }
                        // remember we are now inside an array
                        states.push_back(true);
                        // parse values (no need to call get_token)
                        continue;
                    }
                    case token_type::value_float:
                    {
                        const auto res = m_lexer.get_number_float();
                        if (JSON_HEDLEY_UNLIKELY(!std::isfinite(res)))
{
                            return sax->parse_error(m_lexer.get_position(),
                                                    m_lexer.get_token_string(),
                                                    out_of_range::create(406, "number overflow parsing '" + m_lexer.get_token_string() + "'", BasicJsonType()));
                        }
                        if (JSON_HEDLEY_UNLIKELY(!sax->number_float(res, m_lexer.get_string())))
{
                            return false;
                        }
                        break;
                    }
                    case token_type::literal_false:
                    {
                        if (JSON_HEDLEY_UNLIKELY(!sax->boolean(false)))
{
                            return false;
                        }
                        break;
                    }
                    case token_type::literal_null:
                    {
                        if (JSON_HEDLEY_UNLIKELY(!sax->null()))
{
                            return false;
                        }
                        break;
                    }
                    case token_type::literal_true:
                    {
                        if (JSON_HEDLEY_UNLIKELY(!sax->boolean(true)))
{
                            return false;
                        }
                        break;
                    }
                    case token_type::value_integer:
                    {
                        if (JSON_HEDLEY_UNLIKELY(!sax->number_integer(m_lexer.get_number_integer())))
{
                            return false;
                        }
                        break;
                    }
                    case token_type::value_string:
                    {
                        if (JSON_HEDLEY_UNLIKELY(!sax->string(m_lexer.get_string())))
{
                            return false;
                        }
                        break;
                    }
                    case token_type::value_unsigned:
                    {
                        if (JSON_HEDLEY_UNLIKELY(!sax->number_unsigned(m_lexer.get_number_unsigned())))
{
                            return false;
                        }
                        break;
                    }
                    case token_type::parse_error:
                    {
                        // using "uninitialized" to avoid "expected" message
                        return sax->parse_error(m_lexer.get_position(),
                                                m_lexer.get_token_string(),
                                                parse_error::create(101, m_lexer.get_position(), exception_message(token_type::uninitialized, "value"), BasicJsonType()));
                    }
                    case token_type::uninitialized:
                    case token_type::end_array:
                    case token_type::end_object:
                    case token_type::name_separator:
                    case token_type::value_separator:
                    case token_type::end_of_input:
                    case token_type::literal_or_value:
                    default: // the last token was unexpected
                    {
                        return sax->parse_error(m_lexer.get_position(),
                                                m_lexer.get_token_string(),
                                                parse_error::create(101, m_lexer.get_position(), exception_message(token_type::literal_or_value, "value"), BasicJsonType()));
                    }
                }
            }
            else
            {
                skip_to_state_evaluation = false;
            }
            // we reached this line after we successfully parsed a value
            if (states.empty())
            {
                // empty stack: we reached the end of the hierarchy: done
                return true;
            }
            if (states.back())  // array
            {
                // comma -> next value
                if (get_token() == token_type::value_separator)
                {
                    // parse a new value
                    get_token();
                    continue;
                }
                // closing ]
                if (JSON_HEDLEY_LIKELY(last_token == token_type::end_array))
                {
                    if (JSON_HEDLEY_UNLIKELY(!sax->end_array()))
                    {
                        return false;
                    }
                    // We are done with this array. Before we can parse a
                    // new value, we need to evaluate the new state first.
                    // By setting skip_to_state_evaluation to false, we
                    // are effectively jumping to the beginning of this if.
                    JSON_ASSERT(!states.empty());
                    states.pop_back();
                    skip_to_state_evaluation = true;
                    continue;
                }
                return sax->parse_error(m_lexer.get_position(),
                                        m_lexer.get_token_string(),
                                        parse_error::create(101, m_lexer.get_position(), exception_message(token_type::end_array, "array"), BasicJsonType()));
            }
            // states.back() is false -> object
            // comma -> next value
            if (get_token() == token_type::value_separator)
            {
                // parse key
                if (JSON_HEDLEY_UNLIKELY(get_token() != token_type::value_string))
                {
                    return sax->parse_error(m_lexer.get_position(),
                                            m_lexer.get_token_string(),
                                            parse_error::create(101, m_lexer.get_position(), exception_message(token_type::value_string, "object key"), BasicJsonType()));
                }
                if (JSON_HEDLEY_UNLIKELY(!sax->key(m_lexer.get_string())))
                {
                    return false;
                }
                // parse separator (:)
                if (JSON_HEDLEY_UNLIKELY(get_token() != token_type::name_separator))
                {
                    return sax->parse_error(m_lexer.get_position(),
                                            m_lexer.get_token_string(),
                                            parse_error::create(101, m_lexer.get_position(), exception_message(token_type::name_separator, "object separator"), BasicJsonType()));
                }
                // parse values
                get_token();
                continue;
            }
            // closing }
            if (JSON_HEDLEY_LIKELY(last_token == token_type::end_object))
            {
                if (JSON_HEDLEY_UNLIKELY(!sax->end_object()))
                {
                    return false;
                }
                // We are done with this object. Before we can parse a
                // new value, we need to evaluate the new state first.
                // By setting skip_to_state_evaluation to false, we
                // are effectively jumping to the beginning of this if.
                JSON_ASSERT(!states.empty());
                states.pop_back();
                skip_to_state_evaluation = true;
                continue;
            }
            return sax->parse_error(m_lexer.get_position(),
                                    m_lexer.get_token_string(),
                                    parse_error::create(101, m_lexer.get_position(), exception_message(token_type::end_object, "object"), BasicJsonType()));
        }
    }
References nlohmann::detail::parse_error::create(), nlohmann::detail::out_of_range::create(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::exception_message(), nlohmann::detail::lexer< BasicJsonType, InputAdapterType >::get_number_float(), nlohmann::detail::lexer< BasicJsonType, InputAdapterType >::get_number_integer(), nlohmann::detail::lexer< BasicJsonType, InputAdapterType >::get_number_unsigned(), nlohmann::detail::lexer< BasicJsonType, InputAdapterType >::get_position(), nlohmann::detail::lexer< BasicJsonType, InputAdapterType >::get_string(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::get_token(), nlohmann::detail::lexer< BasicJsonType, InputAdapterType >::get_token_string(), JSON_ASSERT, JSON_HEDLEY_LIKELY, JSON_HEDLEY_UNLIKELY, nlohmann::detail::parser< BasicJsonType, InputAdapterType >::last_token, and nlohmann::detail::parser< BasicJsonType, InputAdapterType >::m_lexer.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse(), and nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse().
Member Data Documentation
allow_exceptions
template<typename BasicJsonType , typename InputAdapterType > const bool nlohmann::detail::parser< BasicJsonType, InputAdapterType >::allow_exceptions = true private
whether to throw exceptions in case of errors
Definition at line 11202 of file json.hpp.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse().
callback
template<typename BasicJsonType , typename InputAdapterType > const parser_callback_t<BasicJsonType> nlohmann::detail::parser< BasicJsonType, InputAdapterType >::callback = nullptr private
callback function
Definition at line 11196 of file json.hpp.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse().
last_token
template<typename BasicJsonType , typename InputAdapterType > token_type nlohmann::detail::parser< BasicJsonType, InputAdapterType >::last_token = token_type::uninitialized private
the type of the last read token
Definition at line 11198 of file json.hpp.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::exception_message(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::get_token(), and nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal().
m_lexer
template<typename BasicJsonType , typename InputAdapterType > lexer_t nlohmann::detail::parser< BasicJsonType, InputAdapterType >::m_lexer private
the lexer
Definition at line 11200 of file json.hpp.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::exception_message(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::get_token(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse(), and nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal().
The documentation for this class was generated from the following file:
include/libecs-cpp/json.hpp