libecs-cpp: PhysicsSystem Class Reference
PhysicsSystem Class Reference
Public Member Functions
PhysicsSystem ()
Json::Value Export ()
void Update ()
Public Member Functions inherited from ecs::System
System ()
System (std::string Handle)
virtual void Init ()
void ResourceAdd (std::string, void *)
void ContainerSet (ecs::Container *Container)
std::string HandleGet ()
ecs::TypeEntityComponentList ComponentsGet ()
void ComponentRequest (std::string)
void MessageSubmit (Json::Value)
Additional Inherited Members
Public Attributes inherited from ecs::System
std::string Handle
ecs::Container * Container = nullptr
Protected Member Functions inherited from ecs::System
uint32_t DeltaTimeGet ()
Protected Attributes inherited from ecs::System
std::vector< std::string > RequestedComponents
std::queue< Json::Value > messages
std::map< std::string, void * > resources
std::chrono::steady_clock::time_point LastTime = std::chrono::steady_clock::now()
Detailed Description
Definition at line 50 of file example.cpp.
Constructor & Destructor Documentation
PhysicsSystem()
PhysicsSystem::PhysicsSystem () inline
Definition at line 53 of file example.cpp.
     {
         this->Handle = "PhysicsSystem";
         this->ComponentRequest("PositionComponent");
         this->ComponentRequest("VelocityComponent");
     }
References ecs::System::ComponentRequest(), and ecs::System::Handle.
Member Function Documentation
Export()
Json::Value PhysicsSystem::Export () inline virtual
Implements ecs::System.
Definition at line 60 of file example.cpp.
     {
         Json::Value config;
         return config;
     }
Update()
void PhysicsSystem::Update () inline virtual
Reimplemented from ecs::System.
Definition at line 66 of file example.cpp.
     {
         /* dt = number of milliseconds since last Update() */
         auto dt = this->DeltaTimeGet();
         std::cout << "Last run " << dt << "ms ago" << std::endl;
         // Get components specified with this->ComponentRequest()...
         auto Components = this->ComponentsGet();
         // ...and cycle through them
         for(auto &[entity, pcomponent] : Components["PositionComponent"])
         {
             // Cast to PositionComponent class
             auto pos = std::dynamic_pointer_cast<PositionComponent>(pcomponent);
             // Get related VelocityComponent
             auto vcomponent = Components["VelocityComponent"][entity];
             auto vel = std::dynamic_pointer_cast<VelocityComponent>(vcomponent);
             // scale velocity
             float multiplier = dt / 1000.0;
             // Adjust position data
             pos->x += vel->x * multiplier;
             pos->y += vel->y * multiplier;
             std::cout << entity << " - Position - x: " << pos->x << ", y: " << pos->y << "   Velocity - x: ";
             std::cout << vel->x << ", y: " << vel->y << "    Multiplier: " << multiplier << std::endl;
         }
     }
References ecs::System::ComponentsGet(), and ecs::System::DeltaTimeGet().
The documentation for this class was generated from the following file:
src/example.cpp