libecs-cpp: ecs::Entity Class Reference
ecs::Entity Class Reference
#include <Entity.hpp>
Public Member Functions
Entity ()
Entity (std::string uuid)
Json::Value Export ()
void ContainerSet (ecs::Container *Container)
std::string HandleGet ()
ecs::TypeEntityComponentList ComponentsGet ()
ecs::TypeEntityComponentList ComponentGet (std::string Type)
std::shared_ptr< ecs::Component > Component (ecs::Component *component)
void destroy ()
Public Attributes
std::string Handle
ecs::Container * Container = nullptr
Private Attributes
ecs::TypeEntityComponentList Components
Detailed Description
Definition at line 13 of file Entity.hpp.
Constructor & Destructor Documentation
Entity() [1/2]
ecs::Entity::Entity ()
Definition at line 6 of file Entity.cpp.
     {
         this->Handle = ecs::Uuid().Get();
     }
References ecs::Uuid::Get(), and Handle.
Entity() [2/2]
ecs::Entity::Entity (std::string uuid)
Definition at line 11 of file Entity.cpp.
     {
         this->Handle = uuid;
     }
References Handle.
Member Function Documentation
Component()
std::shared_ptr< ecs::Component > ecs::Entity::Component (ecs::Component * component)
Definition at line 50 of file Entity.cpp.
     {
         std::shared_ptr<ecs::Component> c(component);
         c->EntityHandle = this->Handle;
         this->Components[c->Type][c->EntityHandle] = c;
         this->Container->Component(c);
         return c;
     }
References ecs::Container::Component(), Components, and Handle.
ComponentGet()
ecs::TypeEntityComponentList ecs::Entity::ComponentGet (std::string Type)
Definition at line 42 of file Entity.cpp.
     {
         ecs::TypeEntityComponentList result;
         result[Type] = this->Components[Type];
         return result;
     }
References Components.
ComponentsGet()
ecs::TypeEntityComponentList ecs::Entity::ComponentsGet ()
Definition at line 37 of file Entity.cpp.
     {
         return this->Components;
     }
References Components.
ContainerSet()
void ecs::Entity::ContainerSet (ecs::Container * Container)
Definition at line 32 of file Entity.cpp.
     {
         this->Container = container;
     }
Referenced by ecs::Container::EntityCreate().
destroy()
void ecs::Entity::destroy ()
Definition at line 59 of file Entity.cpp.
     {
         this->Container->EntityDestroy(this->Handle);
     }
References ecs::Container::EntityDestroy(), and Handle.
Export()
Json::Value ecs::Entity::Export ()
Definition at line 16 of file Entity.cpp.
     {
         Json::Value config;
         config["Handle"] = this->HandleGet();
         for(auto &[type, entity_component_list] : this->Components)
         {
             for(auto &[entity, component] : entity_component_list)
             {
                 config["Components"][type].append(component->Export());
             }
         }
         return config;
     }
References Components, and HandleGet().
HandleGet()
std::string ecs::Entity::HandleGet ()
Definition at line 64 of file Entity.cpp.
     {
         return this->Handle;
     }
References Handle.
Referenced by ecs::Container::EntityCreate(), and Export().
Member Data Documentation
Components
ecs::TypeEntityComponentList ecs::Entity::Components private
Definition at line 28 of file Entity.hpp.
Referenced by Component(), ComponentGet(), ComponentsGet(), and Export().
Container
ecs::Container* ecs::Entity::Container = nullptr
Definition at line 22 of file Entity.hpp.
Handle
std::string ecs::Entity::Handle
Definition at line 20 of file Entity.hpp.
Referenced by Component(), destroy(), Entity(), and HandleGet().
The documentation for this class was generated from the following files:
include/libecs-cpp/Entity.hpp
src/Entity.cpp