libecs-cpp: ecs::Container Class Reference
ecs::Container Class Reference
#include <Container.hpp>
Public Member Functions
Container (ecs::Manager *Manager)
Container (ecs::Manager *Manager, std::string Handle)
void Start ()
void Start (uint32_t)
void SystemsInit ()
ecs::System * System (ecs::System *)
std::vector< std::string > SystemsGet ()
std::shared_ptr< ecs::Component > Component (std::shared_ptr< ecs::Component > c)
void ComponentDestroy (std::string entity, std::string Type)
ecs::Entity * Entity (std::string)
ecs::Entity * Entity ()
ecs::Entity * Entity (ecs::Entity *)
void EntityDestroy (std::string)
nlohmann::json Export ()
void Update ()
void MessageSubmit (nlohmann::json)
void ResourceAdd (std::string, ecs::Resource)
ecs::Resource ResourceGet (std::string)
ecs::Uuid UuidGet ()
Public Attributes
std::unordered_map< std::string, ecs::Entity * > Entities
ecs::Manager * Manager = nullptr
const std::string Handle
ecs::TypeEntityComponentList Components
Private Member Functions
void ThreadFunc ()
ecs::Entity * EntityCreate (std::string)
Private Attributes
uint32_t sleep_interval = 1000000 / 30
std::unordered_map< std::string, ecs::System * > Systems
std::thread ContainerThread
bool ThreadRunning = true
std::unordered_map< std::string, ecs::Resource > resources
UUIDv4::UUIDGenerator< std::mt19937_64 > uuidGenerator
Detailed Description
Definition at line 25 of file Container.hpp.
Constructor & Destructor Documentation
Container() [1/2]
ecs::Container::Container (ecs::Manager * Manager)
Definition at line 8 of file Container.cpp.
                                           :
        Manager(Manager), Handle(ecs::Uuid().Get())
    {
    }
Container() [2/2]
ecs::Container::Container (ecs::Manager * Manager, std::string Handle)
Definition at line 13 of file Container.cpp.
                                                             :
        Manager(manager), Handle(Handle)
    {
    }
Member Function Documentation
Component()
std::shared_ptr< ecs::Component > ecs::Container::Component (std::shared_ptr< ecs::Component > c)
Definition at line 67 of file Container.cpp.
    {
        this->Components[c->Type][c->EntityHandle] = c;
        return c;
    }
References Components.
Referenced by ecs::Entity::Component().
ComponentDestroy()
void ecs::Container::ComponentDestroy (std::string entity, std::string Type)
Definition at line 164 of file Container.cpp.
    {
         this->Components[Type].erase(entity);
    }
References Components.
Referenced by ecs::Entity::ComponentDestroy().
Entity() [1/3]
ecs::Entity * ecs::Container::Entity ()
Definition at line 78 of file Container.cpp.
    {
        return this->EntityCreate(ecs::Uuid().Get());
    }
References EntityCreate().
Entity() [2/3]
ecs::Entity * ecs::Container::Entity (ecs::Entity * e)
Definition at line 83 of file Container.cpp.
    {
        this->Entities[e->Handle] = e;
        return e;
    }
References Entities, and ecs::Entity::Handle.
Entity() [3/3]
ecs::Entity * ecs::Container::Entity (std::string Handle)
Definition at line 73 of file Container.cpp.
    {
        return this->EntityCreate(Handle);
    }
References EntityCreate().
EntityCreate()
ecs::Entity * ecs::Container::EntityCreate (std::string Handle) private
Definition at line 89 of file Container.cpp.
    {
        if(this->Entities.count(Handle) == 0)
        {
            this->Entities[Handle] = new ecs::Entity(this, Handle);
        }
        return this->Entities[Handle];
    }
References Entities, and Handle.
Referenced by Entity().
EntityDestroy()
void ecs::Container::EntityDestroy (std::string Handle)
Definition at line 139 of file Container.cpp.
    {
        for(auto &[type, components] : this->Components)
        {
            components.erase(Handle);
        }
        this->Entities.erase(Handle);
    }
References Components, Entities, and Handle.
Referenced by ecs::Entity::Destroy().
Export()
nlohmann::json ecs::Container::Export ()
Definition at line 30 of file Container.cpp.
    {
        nlohmann::json config;
        config["Handle"] = this->Handle;
        for(auto &[name, entity] : this->Entities)
        {
            config["Entities"][name] = entity->Export();
        }
        for(auto &[name, system] : this->Systems)
        {
            config["Systems"][name] = system->Export();
        }
        return config;
    }
References Entities, Handle, and Systems.
MessageSubmit()
void ecs::Container::MessageSubmit (nlohmann::json message)
Definition at line 126 of file Container.cpp.
    {
        auto dest_system = message["destination"]["system"].get<std::string>();
        if(!this->Systems[dest_system])
        {
            auto err = "ecs::Container(\"" + message["destination"]["container"].get<std::string>() +
                       "\")::MessageSubmit(): System " + dest_system + " not found.";
            throw std::runtime_error(err);
        }
        this->Systems[dest_system]->MessageSubmit(message);
    }
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), and Systems.
ResourceAdd()
void ecs::Container::ResourceAdd (std::string name, ecs::Resource r)
Definition at line 148 of file Container.cpp.
    {
        this->resources[name] = r;
    }
References resources.
ResourceGet()
ecs::Resource ecs::Container::ResourceGet (std::string name)
Definition at line 153 of file Container.cpp.
    {
        if(this->resources.count(name) == 0)
        {
            auto err = "Attempted to access non-existent resource: " + name;
            throw std::runtime_error(err);
        }
        return this->resources[name];
    }
References resources.
Start() [1/2]
void ecs::Container::Start ()
Definition at line 18 of file Container.cpp.
    {
        this->ContainerThread = std::thread(&Container::ThreadFunc, this);
        this->ContainerThread.detach();
    }
References ContainerThread, and ThreadFunc().
Referenced by Start().
Start() [2/2]
void ecs::Container::Start (uint32_t interval)
Definition at line 24 of file Container.cpp.
    {
        this->sleep_interval = interval;
        this->Start();
    }
References sleep_interval, and Start().
System()
ecs::System * ecs::Container::System (ecs::System * system)
Definition at line 49 of file Container.cpp.
    {
        system->Container = this;
        system->Components = &(this->Components);
        this->Systems[system->Handle] = system;
        return system;
    }
References Components, ecs::System::Components, ecs::System::Container, ecs::System::Handle, and Systems.
SystemsGet()
std::vector< std::string > ecs::Container::SystemsGet ()
Definition at line 57 of file Container.cpp.
    {
        std::vector<std::string> Handles;
        for(auto &[name, system] : this->Systems)
            Handles.push_back(name);
        return Handles;
    }
References Systems.
Referenced by SystemsInit(), and Update().
SystemsInit()
void ecs::Container::SystemsInit ()
Definition at line 99 of file Container.cpp.
    {
        for(auto &Handle : this->SystemsGet())
        {
            this->Systems[Handle]->Init();
        }
    }
References Handle, Systems, and SystemsGet().
Referenced by ThreadFunc().
ThreadFunc()
void ecs::Container::ThreadFunc () private
Definition at line 107 of file Container.cpp.
    {
        this->SystemsInit();
        while(this->ThreadRunning)
        {
            usleep(this->sleep_interval);
            this->Update();
        }
    }
References sleep_interval, SystemsInit(), ThreadRunning, and Update().
Referenced by Start().
Update()
void ecs::Container::Update ()
Definition at line 118 of file Container.cpp.
    {
        for(auto &Handle : this->SystemsGet())
        {
            this->Systems[Handle]->Update();
        }
    }
References Handle, Systems, and SystemsGet().
Referenced by ThreadFunc().
UuidGet()
ecs::Uuid ecs::Container::UuidGet ()
Definition at line 169 of file Container.cpp.
    {
        return ecs::Uuid(this->uuidGenerator.getUUID());
    }
References uuidGenerator.
Member Data Documentation
Components
ecs::TypeEntityComponentList ecs::Container::Components
Definition at line 49 of file Container.hpp.
Referenced by Component(), ComponentDestroy(), EntityDestroy(), ecs::Entity::Export(), and System().
ContainerThread
std::thread ecs::Container::ContainerThread private
Definition at line 57 of file Container.hpp.
Referenced by Start().
Entities
std::unordered_map<std::string, ecs::Entity *> ecs::Container::Entities
Definition at line 46 of file Container.hpp.
Referenced by Entity(), EntityCreate(), EntityDestroy(), and Export().
Handle
const std::string ecs::Container::Handle
Definition at line 48 of file Container.hpp.
Referenced by EntityCreate(), EntityDestroy(), Export(), SystemsInit(), and Update().
Manager
ecs::Manager* ecs::Container::Manager = nullptr
Definition at line 47 of file Container.hpp.
resources
std::unordered_map<std::string, ecs::Resource> ecs::Container::resources private
Definition at line 62 of file Container.hpp.
Referenced by ResourceAdd(), and ResourceGet().
sleep_interval
uint32_t ecs::Container::sleep_interval = 1000000 / 30 private
Number of microseconds to sleep between Update() calls
Definition at line 53 of file Container.hpp.
Referenced by Start(), and ThreadFunc().
Systems
std::unordered_map<std::string, ecs::System *> ecs::Container::Systems private
A unique ID for the container
Definition at line 56 of file Container.hpp.
Referenced by Export(), MessageSubmit(), System(), SystemsGet(), SystemsInit(), and Update().
ThreadRunning
bool ecs::Container::ThreadRunning = true private
Definition at line 59 of file Container.hpp.
Referenced by ThreadFunc().
uuidGenerator
UUIDv4::UUIDGenerator<std::mt19937_64> ecs::Container::uuidGenerator private
Definition at line 63 of file Container.hpp.
Referenced by UuidGet().
The documentation for this class was generated from the following files:
include/libecs-cpp/Container.hpp
src/Container.cpp