libecs-cpp: ecs::Timing Class Reference
ecs::Timing Class Reference
#include <Timing.hpp>
Public Member Functions
Timing (uint32_t frequency=1000000/30)
bool ShouldUpdate ()
void SetFrequency (uint32_t frequency)
uint32_t GetFrequency () const
Static Private Member Functions
static uint64_t GetCurrentMicroseconds ()
Private Attributes
uint32_t update_frequency
uint64_t last_update_time
Detailed Description
Definition at line 5 of file Timing.hpp.
Constructor & Destructor Documentation
Timing()
ecs::Timing::Timing (uint32_t frequency = 1000000 / 30) inline
Definition at line 8 of file Timing.hpp.
          : update_frequency(frequency),
            last_update_time(GetCurrentMicroseconds()) {}
Member Function Documentation
GetCurrentMicroseconds()
static uint64_t ecs::Timing::GetCurrentMicroseconds () inline static private
Definition at line 35 of file Timing.hpp.
{
            using namespace std::chrono;
            return duration_cast<microseconds>(
                steady_clock::now().time_since_epoch()
            ).count();
        }
Referenced by ShouldUpdate().
GetFrequency()
uint32_t ecs::Timing::GetFrequency () const inline
Definition at line 27 of file Timing.hpp.
{
            return this->update_frequency;
        }
References update_frequency.
SetFrequency()
void ecs::Timing::SetFrequency (uint32_t frequency) inline
Definition at line 23 of file Timing.hpp.
{
            this->update_frequency = frequency;
        }
References update_frequency.
ShouldUpdate()
bool ecs::Timing::ShouldUpdate () inline
Definition at line 12 of file Timing.hpp.
        {
            uint64_t current_time = GetCurrentMicroseconds();
            if(current_time - this->last_update_time >= this->update_frequency)
            {
                this->last_update_time = current_time;
                return true;
            }
            return false;
        }
References GetCurrentMicroseconds(), last_update_time, and update_frequency.
Referenced by ecs::Container::Update().
Member Data Documentation
last_update_time
uint64_t ecs::Timing::last_update_time private
Definition at line 33 of file Timing.hpp.
Referenced by ShouldUpdate().
update_frequency
uint32_t ecs::Timing::update_frequency private
Definition at line 32 of file Timing.hpp.
Referenced by GetFrequency(), SetFrequency(), and ShouldUpdate().
The documentation for this class was generated from the following file:
include/libecs-cpp/Timing.hpp