libecs-cpp: ecs::System Class Reference
ecs::System Class Reference abstract
#include <System.hpp>
Public Member Functions
System ()
System (std::string Handle)
virtual void Init ()
void ContainerSet (ecs::Container *Container)
ecs::Container * ContainerGet ()
std::string HandleGet ()
virtual void Update ()
ecs::TypeEntityComponentList ComponentsGet ()
void ComponentRequest (std::string)
void MessageSubmit (Json::Value)
virtual Json::Value Export ()=0
Public Attributes
std::string Handle
ecs::Container * Container = nullptr
Protected Member Functions
uint32_t DeltaTimeGet ()
Protected Attributes
std::vector< std::string > RequestedComponents
std::queue< Json::Value > messages
std::chrono::steady_clock::time_point LastTime = std::chrono::steady_clock::now()
Detailed Description
Definition at line 10 of file System.hpp.
Constructor & Destructor Documentation
System() [1/2]
ecs::System::System ()
Definition at line 6 of file System.cpp.
     {
         this->Handle = ecs::Uuid().Get();
     }
References ecs::Uuid::Get(), and Handle.
System() [2/2]
ecs::System::System (std::string Handle)
Definition at line 11 of file System.cpp.
     {
         this->Handle = Handle;
     }
References Handle.
Member Function Documentation
ComponentRequest()
void ecs::System::ComponentRequest (std::string component)
Definition at line 35 of file System.cpp.
     {
         for(auto &s : this->RequestedComponents)
         {
             if(s == component) return;
         }
         RequestedComponents.push_back(component);
     }
References RequestedComponents.
ComponentsGet()
ecs::TypeEntityComponentList ecs::System::ComponentsGet ()
Definition at line 44 of file System.cpp.
     {
         return this->Container->ComponentsGet(this->RequestedComponents);
     }
References ecs::Container::ComponentsGet(), and RequestedComponents.
ContainerGet()
ecs::Container * ecs::System::ContainerGet ()
Definition at line 30 of file System.cpp.
     {
         return this->Container;
     }
References Container.
ContainerSet()
void ecs::System::ContainerSet (ecs::Container * Container)
Definition at line 25 of file System.cpp.
     {
         this->Container = container;
     }
Referenced by ecs::Container::System().
DeltaTimeGet()
uint32_t ecs::System::DeltaTimeGet () protected
Definition at line 54 of file System.cpp.
     {
         std::chrono::steady_clock::time_point now = std::chrono::steady_clock::now();
         uint32_t dt = std::chrono::duration_cast<std::chrono::milliseconds>(now - this->LastTime).count();
         this->LastTime = now;
         return dt;
     }
References LastTime.
Export()
virtual Json::Value ecs::System::Export () pure virtual
HandleGet()
std::string ecs::System::HandleGet ()
Definition at line 20 of file System.cpp.
     {
         return this->Handle;
     }
References Handle.
Referenced by ecs::Container::System().
Init()
void ecs::System::Init () virtual
Definition at line 16 of file System.cpp.
     {
     }
MessageSubmit()
void ecs::System::MessageSubmit (Json::Value message)
Definition at line 49 of file System.cpp.
     {
         this->messages.push(message);
     }
References messages.
Update()
virtual void ecs::System::Update () inline virtual
Definition at line 19 of file System.hpp.
 {};
Member Data Documentation
Container
ecs::Container* ecs::System::Container = nullptr
Definition at line 21 of file System.hpp.
Referenced by ContainerGet().
Handle
std::string ecs::System::Handle
Definition at line 20 of file System.hpp.
Referenced by HandleGet(), and System().
LastTime
std::chrono::steady_clock::time_point ecs::System::LastTime = std::chrono::steady_clock::now() protected
Definition at line 29 of file System.hpp.
Referenced by DeltaTimeGet().
messages
std::queue<Json::Value> ecs::System::messages protected
Definition at line 28 of file System.hpp.
Referenced by MessageSubmit().
RequestedComponents
std::vector<std::string> ecs::System::RequestedComponents protected
Definition at line 27 of file System.hpp.
Referenced by ComponentRequest(), and ComponentsGet().
The documentation for this class was generated from the following files:
include/libecs-cpp/System.hpp
src/System.cpp