libecs-cpp: ecs::Manager Class Reference
ecs::Manager Class Reference
#include <Manager.hpp>
Public Member Functions
Manager ()
ecs::Container * Container (std::string handle)
ecs::Container * Container ()
std::vector< std::string > ContainersGet ()
bool IsRunning ()
void Shutdown ()
void MessageSubmit (Json::Value)
Private Member Functions
void ContainersKill (std::vector< std::string >)
ecs::Container * ContainerCreate (std::string handle)
Private Attributes
std::unordered_map< std::string, ecs::Container * > containers
std::mutex mutex_containers
bool Running = true
Detailed Description
Manages containers.
Definition at line 21 of file Manager.hpp.
Constructor & Destructor Documentation
Manager()
ecs::Manager::Manager ()
Definition at line 7 of file Manager.cpp.
     {
     }
Member Function Documentation
Container() [1/2]
ecs::Container * ecs::Manager::Container ()
Definition at line 16 of file Manager.cpp.
     {
         return this->ContainerCreate("");
     }
References ContainerCreate().
Container() [2/2]
ecs::Container * ecs::Manager::Container (std::string handle)
Definition at line 11 of file Manager.cpp.
     {
         return this->ContainerCreate(handle);
     }
References ContainerCreate().
ContainerCreate()
ecs::Container * ecs::Manager::ContainerCreate (std::string handle) private
Definition at line 31 of file Manager.cpp.
     {
         ecs::Container *c;
         this->mutex_containers.lock();
         {
             if(handle.size() == 0)
             {
                 c = new ecs::Container();
                 this->containers[c->HandleGet()] = c;
             }
             else
             {
                 if(this->containers.count(handle) == 0)
                 {
                     c = new ecs::Container(handle);
                     this->containers[handle] = c;
                 }
                 else c = this->containers[handle];
             }
             c->ManagerSet(this);
         }
         this->mutex_containers.unlock();
         return c;
     }
References containers, ecs::Container::HandleGet(), ecs::Container::ManagerSet(), and mutex_containers.
Referenced by Container().
ContainersGet()
std::vector< std::string > ecs::Manager::ContainersGet ()
Definition at line 57 of file Manager.cpp.
     {
         std::vector<std::string> handles;
         for(auto &c : this->containers)
             handles.push_back(c.first);
         return handles;
     }
References containers.
ContainersKill()
void ecs::Manager::ContainersKill (std::vector< std::string > handles) private
Definition at line 67 of file Manager.cpp.
     {
         this->mutex_containers.lock();
         {
             for(auto &h : handles)
             {
                 delete this->containers[h];
             }
         }
         this->mutex_containers.unlock();
     }
References containers, and mutex_containers.
IsRunning()
bool ecs::Manager::IsRunning ()
Definition at line 21 of file Manager.cpp.
     {
         return Running;
     }
References Running.
MessageSubmit()
void ecs::Manager::MessageSubmit (Json::Value message)
Definition at line 79 of file Manager.cpp.
     {
         auto dest_container = message["destination"]["container"].asString();
         if(!this->containers[dest_container])
         {
             auto err = "ecs::Manager::MessageSubmit(): Container " + dest_container + " not found.";
             throw std::runtime_error(err);
         }
         this->containers[dest_container]->MessageSubmit(message);
     }
References containers.
Shutdown()
void ecs::Manager::Shutdown ()
Definition at line 26 of file Manager.cpp.
     {
         this->Running = false;
     }
References Running.
Member Data Documentation
containers
std::unordered_map<std::string, ecs::Container *> ecs::Manager::containers private
Definition at line 34 of file Manager.hpp.
Referenced by ContainerCreate(), ContainersGet(), ContainersKill(), and MessageSubmit().
mutex_containers
std::mutex ecs::Manager::mutex_containers private
Definition at line 35 of file Manager.hpp.
Referenced by ContainerCreate(), and ContainersKill().
Running
bool ecs::Manager::Running = true private
Definition at line 36 of file Manager.hpp.
Referenced by IsRunning(), and Shutdown().
The documentation for this class was generated from the following files:
include/libecs-cpp/Manager.hpp
src/Manager.cpp