libecs-cpp: ecs::Uuid Class Reference
ecs::Uuid Class Reference
#include <Uuid.hpp>
Public Member Functions
Uuid ()
Uuid (std::string)
std::string Get ()
Private Attributes
std::string uuid
Detailed Description
Definition at line 12 of file Uuid.hpp.
Constructor & Destructor Documentation
Uuid() [1/2]
ecs::Uuid::Uuid ()
Definition at line 6 of file Uuid.cpp.
     {
         this->uuid.resize(36);
 #ifdef _WIN32
         UUID id;
         UuidCreate(&id);
         RPC_CSTR szUuid = NULL;
         if(UuidToString(&id, &szUuid) == RPC_S_OK)
         {
             this->uuid = (char*) szUuid;
             RpcStringFree(&szUuid);
         }
 #else
         uuid_t id;
         uuid_generate(id);
         uuid_unparse(id, &this->uuid[0]);
 #endif
     }
References uuid.
Uuid() [2/2]
ecs::Uuid::Uuid (std::string id)
Definition at line 26 of file Uuid.cpp.
     {
         this->uuid = id;
     }
References uuid.
Member Function Documentation
Get()
std::string ecs::Uuid::Get ()
Definition at line 31 of file Uuid.cpp.
     {
         return this->uuid;
     }
References uuid.
Referenced by ecs::Component::Component(), ecs::Container::Container(), ecs::Entity::Entity(), and ecs::System::System().
Member Data Documentation
uuid
std::string ecs::Uuid::uuid private
Definition at line 19 of file Uuid.hpp.
Referenced by Get(), and Uuid().
The documentation for this class was generated from the following files:
include/libecs-cpp/Uuid.hpp
src/Uuid.cpp