libecs-cpp: src/example.cpp File Reference
example.cpp File Reference
#include <libecs-cpp/ecs.hpp>
#include <iostream>
Classes
class PositionComponent
class VelocityComponent
class PhysicsSystem
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 98 of file example.cpp.
 {
     auto world = ECS->Container();
     world->System(new PhysicsSystem());
     /* Create a new entity in the 'world' container */
     auto e = world->Entity();
     /* Initialize a PositionComponent and add it to the Entity 'e' */
     Json::Value config;
     config["x"] = 1;
     config["y"] = 1;
     e->Component(new PositionComponent(config));
     /* Initialize a VelocityComponent and add it to the Entity 'e' */
     config["x"] = 1; // meters per second
     config["y"] = 0;
     e->Component(new VelocityComponent(config));
     /* Run container in its own thread */
     bool threaded = true;
     /*                   OR               */
     /* Run container loop in main thread, */
     /* OS X won't let GUI stuff happen    */
     /* outside the main thread)           */
 #if __APPLE__
     threaded = false;
 #endif
     if(threaded) world->Start();
     else world->SystemsInit();
     std::cout << world->Export() << std::endl;
     while(ECS->IsRunning())
     {
         usleep(100000);
         if(!threaded) world->Update();
     }
     return 0;
 }
References ecs::Manager::Container(), ECS, ecs::System::Export(), ecs::Manager::IsRunning(), and ecs::Container::System().