libecs-cpp: nlohmann::ordered_map< Key, T, IgnoredLess, Allocator > Struct Template Reference
nlohmann::ordered_map< Key, T, IgnoredLess, Allocator > Struct Template Reference
a minimal map-like container that preserves insertion order
#include <json.hpp>
Public Types
using key_type = Key
using mapped_type = T
using Container = std::vector< std::pair< const Key, T >, Allocator >
using iterator = typename Container::iterator
using const_iterator = typename Container::const_iterator
using size_type = typename Container::size_type
using value_type = typename Container::value_type
template<typename InputIt >
using require_input_iter = typename std::enable_if< std::is_convertible< typename std::iterator_traits< InputIt >::iterator_category, std::input_iterator_tag >::value >::type
Public Member Functions
ordered_map (const Allocator &alloc=Allocator())
template<class It >
ordered_map (It first, It last, const Allocator &alloc=Allocator())
ordered_map (std::initializer_list< T > init, const Allocator &alloc=Allocator())
std::pair< iterator, bool > emplace (const key_type &key, T &&t)
T & operator[] (const Key &key)
const T & operator[] (const Key &key) const
T & at (const Key &key)
const T & at (const Key &key) const
size_type erase (const Key &key)
iterator erase (iterator pos)
iterator erase (iterator first, iterator last)
size_type count (const Key &key) const
iterator find (const Key &key)
const_iterator find (const Key &key) const
std::pair< iterator, bool > insert (value_type &&value)
std::pair< iterator, bool > insert (const value_type &value)
template<typename InputIt , typename = require_input_iter<InputIt>>
void insert (InputIt first, InputIt last)
Detailed Description
template<class Key, class T, class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>>
struct nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >
a minimal map-like container that preserves insertion order
See also
https://json.nlohmann.me/api/ordered_map/
ordered_map: a minimal map-like container that preserves insertion order for use within nlohmann::basic_json<ordered_map>
Definition at line 17039 of file json.hpp.
Member Typedef Documentation
const_iterator
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> using nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::const_iterator = typename Container::const_iterator
Definition at line 17045 of file json.hpp.
Container
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> using nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::Container = std::vector<std::pair<const Key, T>, Allocator>
Definition at line 17043 of file json.hpp.
iterator
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> using nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::iterator = typename Container::iterator
Definition at line 17044 of file json.hpp.
key_type
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> using nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::key_type = Key
Definition at line 17041 of file json.hpp.
mapped_type
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> using nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::mapped_type = T
Definition at line 17042 of file json.hpp.
require_input_iter
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> template<typename InputIt > using nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::require_input_iter = typename std::enable_if<std::is_convertible<typename std::iterator_traits<InputIt>::iterator_category, std::input_iterator_tag>::value>::type
Definition at line 17234 of file json.hpp.
size_type
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> using nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::size_type = typename Container::size_type
Definition at line 17046 of file json.hpp.
value_type
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> using nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::value_type = typename Container::value_type
Definition at line 17047 of file json.hpp.
Constructor & Destructor Documentation
ordered_map() [1/3]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::ordered_map (const Allocator & alloc = Allocator()) inline
Definition at line 17051 of file json.hpp.
 : Container{alloc} {}
ordered_map() [2/3]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> template<class It > nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::ordered_map (It first, It last, const Allocator & alloc = Allocator()) inline
Definition at line 17053 of file json.hpp.
         : Container{first, last, alloc} {}
ordered_map() [3/3]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::ordered_map (std::initializer_list< T > init, const Allocator & alloc = Allocator()) inline
Definition at line 17055 of file json.hpp.
         : Container{init, alloc} {}
Member Function Documentation
at() [1/2]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> T& nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::at (const Key & key) inline
Definition at line 17081 of file json.hpp.
     {
         for (auto it = this->begin(); it != this->end(); ++it)
         {
             if (it->first == key)
             {
                 return it->second;
             }
         }
         JSON_THROW(std::out_of_range("key not found"));
     }
References JSON_THROW.
Referenced by nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::operator[]().
at() [2/2]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> const T& nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::at (const Key & key) const inline
Definition at line 17094 of file json.hpp.
     {
         for (auto it = this->begin(); it != this->end(); ++it)
         {
             if (it->first == key)
             {
                 return it->second;
             }
         }
         JSON_THROW(std::out_of_range("key not found"));
     }
References JSON_THROW.
count()
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> size_type nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::count (const Key & key) const inline
Definition at line 17179 of file json.hpp.
     {
         for (auto it = this->begin(); it != this->end(); ++it)
         {
             if (it->first == key)
             {
                 return 1;
             }
         }
         return 0;
     }
emplace()
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> std::pair<iterator, bool> nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::emplace (const key_type & key, T && t) inline
Definition at line 17058 of file json.hpp.
     {
         for (auto it = this->begin(); it != this->end(); ++it)
         {
             if (it->first == key)
             {
                 return {it, false};
             }
         }
         Container::emplace_back(key, t);
         return {--this->end(), true};
     }
Referenced by nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::insert(), and nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::operator[]().
erase() [1/3]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> size_type nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::erase (const Key & key) inline
Definition at line 17107 of file json.hpp.
     {
         for (auto it = this->begin(); it != this->end(); ++it)
         {
             if (it->first == key)
             {
                 // Since we cannot move const Keys, re-construct them in place
                 for (auto next = it; ++next != this->end(); ++it)
                 {
                     it->~value_type(); // Destroy but keep allocation
                     new (&*it) value_type{std::move(*next)};
                 }
                 Container::pop_back();
                 return 1;
             }
         }
         return 0;
     }
Referenced by nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::erase().
erase() [2/3]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> iterator nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::erase (iterator first, iterator last) inline
Definition at line 17131 of file json.hpp.
     {
         const auto elements_affected = std::distance(first, last);
         const auto offset = std::distance(Container::begin(), first);
         // This is the start situation. We need to delete elements_affected
         // elements (3 in this example: e, f, g), and need to return an
         // iterator past the last deleted element (h in this example).
         // Note that offset is the distance from the start of the vector
         // to first. We will need this later.
         // [ a, b, c, d, e, f, g, h, i, j ]
         //               ^        ^
         //             first    last
         // Since we cannot move const Keys, we re-construct them in place.
         // We start at first and re-construct (viz. copy) the elements from
         // the back of the vector. Example for first iteration:
         //               ,--------.
         //               v        |   destroy e and re-construct with h
         // [ a, b, c, d, e, f, g, h, i, j ]
         //               ^        ^
         //               it       it + elements_affected
         for (auto it = first; std::next(it, elements_affected) != Container::end(); ++it)
         {
             it->~value_type(); // destroy but keep allocation
             new (&*it) value_type{std::move(*std::next(it, elements_affected))}; // "move" next element to it
         }
         // [ a, b, c, d, h, i, j, h, i, j ]
         //               ^        ^
         //             first    last
         // remove the unneeded elements at the end of the vector
         Container::resize(this->size() - static_cast<size_type>(elements_affected));
         // [ a, b, c, d, h, i, j ]
         //               ^        ^
         //             first    last
         // first is now pointing past the last deleted element, but we cannot
         // use this iterator, because it may have been invalidated by the
         // resize call. Instead, we can return begin() + offset.
         return Container::begin() + offset;
     }
erase() [3/3]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> iterator nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::erase (iterator pos) inline
Definition at line 17126 of file json.hpp.
     {
         return erase(pos, std::next(pos));
     }
References nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::erase().
find() [1/2]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> iterator nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::find (const Key & key) inline
Definition at line 17191 of file json.hpp.
     {
         for (auto it = this->begin(); it != this->end(); ++it)
         {
             if (it->first == key)
             {
                 return it;
             }
         }
         return Container::end();
     }
find() [2/2]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> const_iterator nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::find (const Key & key) const inline
Definition at line 17203 of file json.hpp.
     {
         for (auto it = this->begin(); it != this->end(); ++it)
         {
             if (it->first == key)
             {
                 return it;
             }
         }
         return Container::end();
     }
insert() [1/3]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> std::pair<iterator, bool> nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::insert (const value_type & value) inline
Definition at line 17220 of file json.hpp.
     {
         for (auto it = this->begin(); it != this->end(); ++it)
         {
             if (it->first == value.first)
             {
                 return {it, false};
             }
         }
         Container::push_back(value);
         return {--this->end(), true};
     }
insert() [2/3]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> template<typename InputIt , typename = require_input_iter<InputIt>> void nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::insert (InputIt first, InputIt last) inline
Definition at line 17238 of file json.hpp.
     {
         for (auto it = first; it != last; ++it)
         {
             insert(*it);
         }
     }
References nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::insert().
insert() [3/3]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> std::pair<iterator, bool> nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::insert (value_type && value) inline
Definition at line 17215 of file json.hpp.
     {
         return emplace(value.first, std::move(value.second));
     }
References nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::emplace().
Referenced by nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::insert().
operator[]() [1/2]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> T& nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::operator[] (const Key & key) inline
Definition at line 17071 of file json.hpp.
     {
         return emplace(key, T{}).first->second;
     }
References nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::emplace().
operator[]() [2/2]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> const T& nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::operator[] (const Key & key) const inline
Definition at line 17076 of file json.hpp.
     {
         return at(key);
     }
References nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::at().
The documentation for this struct was generated from the following file:
include/libecs-cpp/json.hpp