libecs-cpp: tests/test_Manager.cpp File Reference
test_Manager.cpp File Reference
#include <catch2/catch.hpp>
#include <libecs-cpp/ecs.hpp>
Classes
class TestSystem
Macros
#define CATCH_CONFIG_MAIN
Functions
TEST_CASE ("Manager starts with no containers", "[Manager]")
TEST_CASE ("Manager can create and retrieve containers", "[Manager]")
TEST_CASE ("Manager is running after construction", "[Manager]")
TEST_CASE ("Manager can shut down", "[Manager]")
TEST_CASE ("Manager can submit messages", "[Manager]")
Macro Definition Documentation
CATCH_CONFIG_MAIN
#define CATCH_CONFIG_MAIN
Definition at line 1 of file test_Manager.cpp.
Function Documentation
TEST_CASE() [1/5]
TEST_CASE ("Manager can create and retrieve containers" , "" [Manager])
Definition at line 26 of file test_Manager.cpp.
{
    ecs::Manager manager;
    auto container = manager.Container();
    REQUIRE(container != nullptr);
    REQUIRE_FALSE(manager.ContainersGet().empty());
}
References ecs::Manager::Container(), and ecs::Manager::ContainersGet().
TEST_CASE() [2/5]
TEST_CASE ("Manager can shut down" , "" [Manager])
Definition at line 38 of file test_Manager.cpp.
{
    ecs::Manager manager;
    manager.Shutdown();
    REQUIRE_FALSE(manager.IsRunning());
}
References ecs::Manager::IsRunning(), and ecs::Manager::Shutdown().
TEST_CASE() [3/5]
TEST_CASE ("Manager can submit messages" , "" [Manager])
Definition at line 44 of file test_Manager.cpp.
{
    ecs::Manager manager;
    std::string container_name = "Container 1";
    manager.Container(container_name)->System(new TestSystem());
    nlohmann::json message;
    message["destination"]["container"] = container_name;
    message["destination"]["system"] = "TestSystem";
    REQUIRE_NOTHROW(manager.MessageSubmit(message));
}
References ecs::Manager::Container(), ecs::Manager::MessageSubmit(), and ecs::Container::System().
TEST_CASE() [4/5]
TEST_CASE ("Manager is running after construction" , "" [Manager])
Definition at line 33 of file test_Manager.cpp.
{
    ecs::Manager manager;
    REQUIRE(manager.IsRunning());
}
References ecs::Manager::IsRunning().
TEST_CASE() [5/5]
TEST_CASE ("Manager starts with no containers" , "" [Manager])
Definition at line 21 of file test_Manager.cpp.
{
    ecs::Manager manager;
    REQUIRE(manager.ContainersGet().empty());
}
References ecs::Manager::ContainersGet().