libecs-cpp: tests/test_System.cpp File Reference
test_System.cpp File Reference
#include <catch2/catch.hpp>
#include <libecs-cpp/ecs.hpp>
Classes
class TestSystem
Macros
#define CATCH_CONFIG_MAIN
Functions
TEST_CASE ("System is initialized with a valid handle", "[System]")
TEST_CASE ("System can be initialized with a custom handle", "[System]")
TEST_CASE ("System starts with no messages", "[System]")
TEST_CASE ("System can submit messages", "[System]")
TEST_CASE ("System can calculate delta time", "[System]")
Macro Definition Documentation
CATCH_CONFIG_MAIN
#define CATCH_CONFIG_MAIN
Definition at line 1 of file test_System.cpp.
Function Documentation
TEST_CASE() [1/5]
TEST_CASE ("System can be initialized with a custom handle" , "" [System])
Definition at line 31 of file test_System.cpp.
{
    std::string customHandle = "custom_handle";
    TestSystem system(customHandle);
    REQUIRE(system.Handle == customHandle);
}
References ecs::System::Handle.
TEST_CASE() [2/5]
TEST_CASE ("System can calculate delta time" , "" [System])
Definition at line 49 of file test_System.cpp.
{
    TestSystem system;
    // First call to initialize LastTime
    system.DeltaTimeGet();
    // Small sleep to simulate passage of time
    std::this_thread::sleep_for(std::chrono::milliseconds(10));
    uint32_t deltaTime = system.DeltaTimeGet();
    REQUIRE(deltaTime >= 10); // Check if at least 10ms have passed
}
References ecs::System::DeltaTimeGet().
TEST_CASE() [3/5]
TEST_CASE ("System can submit messages" , "" [System])
Definition at line 42 of file test_System.cpp.
{
    TestSystem system;
    nlohmann::json message = {{"key", "value"}};
    system.MessageSubmit(message);
    REQUIRE(system.MessagesWaiting() == 1);
}
References ecs::System::MessageSubmit(), and ecs::System::MessagesWaiting().
TEST_CASE() [4/5]
TEST_CASE ("System is initialized with a valid handle" , "" [System])
Definition at line 26 of file test_System.cpp.
{
    TestSystem system;
    REQUIRE_FALSE(system.Handle.empty());
}
References ecs::System::Handle.
TEST_CASE() [5/5]
TEST_CASE ("System starts with no messages" , "" [System])
Definition at line 37 of file test_System.cpp.
{
    TestSystem system;
    REQUIRE(system.MessagesWaiting() == 0);
}
References ecs::System::MessagesWaiting().