libecs-cpp: tests/test_Entity.cpp File Reference
test_Entity.cpp File Reference
#include <catch2/catch.hpp>
#include <libecs-cpp/ecs.hpp>
Classes
class TestComponent
Macros
#define CATCH_CONFIG_MAIN
Functions
TEST_CASE ("Entity is created with a unique handle", "[Entity]")
TEST_CASE ("Entity can be created with a custom handle", "[Entity]")
TEST_CASE ("Entity exports its data correctly", "[Entity]")
TEST_CASE ("Entity can add and retrieve a component", "[Entity]")
TEST_CASE ("Entity can destroy a component", "[Entity]")
TEST_CASE ("Entity can be destroyed", "[Entity]")
Macro Definition Documentation
CATCH_CONFIG_MAIN
#define CATCH_CONFIG_MAIN
Definition at line 1 of file test_Entity.cpp.
Function Documentation
TEST_CASE() [1/6]
TEST_CASE ("Entity can add and retrieve a component" , "" [Entity])
Definition at line 49 of file test_Entity.cpp.
{
    auto container = ECS->Container();
    auto entity = container->Entity();
    nlohmann::json config;
    config["value"] = 5;
    //auto component = std::make_shared<TestComponent>(config);
    entity->Component(new TestComponent(config));
    auto retrievedComponent = container->Components["TestComponent"][entity->Handle];
    REQUIRE(retrievedComponent != nullptr);
}
References ecs::Manager::Container(), ECS, and ecs::Container::Entity().
TEST_CASE() [2/6]
TEST_CASE ("Entity can be created with a custom handle" , "" [Entity])
Definition at line 35 of file test_Entity.cpp.
{
    std::string customHandle = "myEntity";
    auto container = ECS->Container();
    auto entity = container->Entity(customHandle);
    REQUIRE(entity->Handle == customHandle);
}
References ecs::Manager::Container(), ECS, and ecs::Container::Entity().
TEST_CASE() [3/6]
TEST_CASE ("Entity can be destroyed" , "" [Entity])
Definition at line 71 of file test_Entity.cpp.
{
    auto container = ECS->Container();
    auto entity = container->Entity();
    std::string handle = entity->Handle;
    entity->Destroy();
    // Assuming there is a way to check if an entity has been destroyed, e.g.:
    REQUIRE(container->Entities[handle] == nullptr);
}
References ecs::Manager::Container(), ECS, ecs::Container::Entity(), and ecs::Entity::Handle.
TEST_CASE() [4/6]
TEST_CASE ("Entity can destroy a component" , "" [Entity])
Definition at line 60 of file test_Entity.cpp.
{
    auto container = ECS->Container();
    auto entity = container->Entity();
    nlohmann::json config;
    config["value"] = 5;
    entity->Component(new TestComponent(config));
    entity->ComponentDestroy("TestComponent");
    auto retrievedComponent = container->Components["TestComponent"][entity->Handle];
    REQUIRE(retrievedComponent == nullptr);
}
References ecs::Manager::Container(), ECS, and ecs::Container::Entity().
TEST_CASE() [5/6]
TEST_CASE ("Entity exports its data correctly" , "" [Entity])
Definition at line 42 of file test_Entity.cpp.
{
    auto container = ECS->Container();
    auto entity = container->Entity();
    nlohmann::json exportedData = entity->Export();
    REQUIRE(exportedData["Handle"] == entity->Handle);
}
References ecs::Manager::Container(), ECS, and ecs::Container::Entity().
TEST_CASE() [6/6]
TEST_CASE ("Entity is created with a unique handle" , "" [Entity])
Definition at line 29 of file test_Entity.cpp.
{
    auto container = ECS->Container();
    auto entity = container->Entity();
    REQUIRE_FALSE(entity->Handle.empty());
}
References ecs::Manager::Container(), ECS, and ecs::Container::Entity().